<a href="https://colab.research.google.com/github/antonypradeep54/Machine-Learning---Company-bankruptcy-prediction/blob/main/C4_M30_L2_Project_Company_Bankruptcy_Completed_on_06_Sep_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<font size=+3 color="blue"><center><b> Project : Company Bankruptcy</b></center></font>

## Table of contents

- Problem statement
- Libraries and functions
- Import dataset
- Exploratory Data Analysis (EDA)
    - Check for missing data
    - Correlation Analysis
    - Handle target class imbalance
- Model training and evaluation
    - Logistic Regression
    - K-Nearest Neighbors
    - Decision Tree
    - Neural Networks
    - Random Forest
    - Gradient Boosting
- Comparison of Results
- References

##Problem Statement
The goal is to build and evaluate machine learning models to predict company bankruptcy based on various financial indicators. The task involves addressing class imbalance in the dataset to improve model performance, particularly for predicting companies that are at risk of bankruptcy (minority class).

##Libraries and functions

In [ ]:
import pandas as pd
import numpy as np
from google.colab import files
import os

##Import dataset

In [ ]:
upoaded = files.upload()

Saving Dataset.csv to Dataset.csv


In [ ]:
print(os.listdir())

['.config', 'Dataset.csv', 'dataset', 'sample_data']


In [ ]:
# Creates the "dataset" directory if it doesn't exist
os.makedirs("dataset", exist_ok=True)

# Imports the shutil module, which provides functions for file and directory operations.
import shutil

# This moves the file nyc_taxi_trip_duration.csv from its current location to the dataset/ folder.
shutil.move("Dataset.csv", "dataset/Dataset.csv")

'dataset/Dataset.csv'

In [ ]:
Company_data_df = pd.read_csv('dataset/Dataset.csv')
Company_data_df.head()

Bankrupt?   ROA(C) before interest and depreciation before interest  \
0          1                                           0.370594          
1          1                                           0.464291          
2          1                                           0.426071          
3          1                                           0.399844          
4          1                                           0.465022          

    ROA(A) before interest and % after tax  \
0                                 0.424389   
1                                 0.538214   
2                                 0.499019   
3                                 0.451265   
4                                 0.538432   

    ROA(B) before interest and depreciation after tax  \
0                                           0.405750    
1                                           0.516730    
2                                           0.472295    
3                                           0.457733    
4                                           0.522298    

    Operating Gross Margin   Realized Sales Gross Margin  \
0                 0.601457                      0.601457   
1                 0.610235                      0.610235   
2                 0.601450                      0.601364   
3                 0.583541                      0.583541   
4                 0.598783                      0.598783   

    Operating Profit Rate   Pre-tax net Interest Rate  \
0                0.998969                    0.796887   
1                0.998946                    0.797380   
2                0.998857                    0.796403   
3                0.998700                    0.796967   
4                0.998973                    0.797366   

    After-tax net Interest Rate   Non-industry income and expenditure/revenue  \
0                      0.808809                                      0.302646   
1                      0.809301                                      0.303556   
2                      0.808388                                      0.302035   
3                      0.808966                                      0.303350   
4                      0.809304                                      0.303475   

   ...   Net Income to Total Assets   Total assets to GNP price  \
0  ...                     0.716845                    0.009219   
1  ...                     0.795297                    0.008323   
2  ...                     0.774670                    0.040003   
3  ...                     0.739555                    0.003252   
4  ...                     0.795016                    0.003878   

    No-credit Interval   Gross Profit to Sales  \
0             0.622879                0.601453   
1             0.623652                0.610237   
2             0.623841                0.601449   
3             0.622929                0.583538   
4             0.623521                0.598782   

    Net Income to Stockholder's Equity   Liability to Equity  \
0                             0.827890              0.290202   
1                             0.839969              0.283846   
2                             0.836774              0.290189   
3                             0.834697              0.281721   
4                             0.839973              0.278514   

    Degree of Financial Leverage (DFL)  \
0                             0.026601   
1                             0.264577   
2                             0.026555   
3                             0.026697   
4                             0.024752   

    Interest Coverage Ratio (Interest expense to EBIT)   Net Income Flag  \
0                                           0.564050                   1   
1                                           0.570175                   1   
2                                           0.563706                   1   
3                                           0.564663                   1   
4                        

##Exploratory Data Analysis (EDA)

The first column "Bankrupt?" is our target variables (dependent variable) and other columns are features (independent variables).

In [ ]:
num_columns = Company_data_df.shape[1]
print(f"There are {num_columns} columns, lets explore if there are columns which we can drop due to missing data.")

There are 96 columns, lets explore if there are columns which we can drop due to missing data.


####Check for missing data

In [ ]:
# Count missing values per column
missing_counts = Company_data_df.isnull().sum()

# Percentage of missing values
missing_percentage = (Company_data_df.isnull().mean() * 100).round(2)

# Combine into one DataFrame for clarity
missing_summary = pd.DataFrame({
    "Missing_Values": missing_counts,
    "Missing_Percentage": missing_percentage
}).sort_values(by="Missing_Percentage", ascending=False)


Count_columns_with_more_than_50_percent_missing_values = (missing_summary['Missing_Percentage'] > 50).sum()

print(f"There are {Count_columns_with_more_than_50_percent_missing_values} columns with more than 50% missing values, so we dont need to drop any columns.")

There are 0 columns with more than 50% missing values, so we dont need to drop any columns.


####Correlation Analysis

In [ ]:
target_corr = corr_matrix['Bankrupt?'].sort_values(ascending=False)
print(target_corr)

Bankrupt?                                                   1.000000
 Net Income to Total Assets                                 0.315457
 ROA(A) before interest and % after tax                     0.282941
 ROA(B) before interest and depreciation after tax          0.273051
 ROA(C) before interest and depreciation before interest    0.260807
                                                              ...   
 Long-term Liability to Current Assets                      0.000778
 Cash Flow to Sales                                         0.000479
 Realized Sales Gross Profit Growth Rate                    0.000458
 Operating Profit Rate                                      0.000230
 Net Income Flag                                                 NaN
Name: Bankrupt?, Length: 96, dtype: float64


In [ ]:
# Absolute correlation matrix
corr_matrix = Company_data_df.corr().abs()

# Select upper triangle of correlation matrix
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))

In [ ]:
# Find features with correlation > 0.9
to_drop = [column for column in upper.columns if any(upper[column] > 0.9)]

high_corr_pairs = []

threshold = 0.9

for col in to_drop:
    correlated_with = list(upper.index[upper[col] > threshold])
    high_corr_pairs.append((col, correlated_with))

for col, corr_cols in high_corr_pairs:
    print(f"\n{col} is highly correlated with:   {corr_cols}")



 ROA(A) before interest and % after tax is highly correlated with:   [' ROA(C) before interest and depreciation before interest']

 ROA(B) before interest and depreciation after tax is highly correlated with:   [' ROA(C) before interest and depreciation before interest', ' ROA(A) before interest and % after tax']

 Realized Sales Gross Margin is highly correlated with:   [' Operating Gross Margin']

 Pre-tax net Interest Rate is highly correlated with:   [' Operating Profit Rate']

 After-tax net Interest Rate is highly correlated with:   [' Pre-tax net Interest Rate']

 Continuous interest rate (after tax) is highly correlated with:   [' Operating Profit Rate', ' Pre-tax net Interest Rate', ' After-tax net Interest Rate']

 Net Value Per Share (A) is highly correlated with:   [' Net Value Per Share (B)']

 Net Value Per Share (C) is highly correlated with:   [' Net Value Per Share (B)', ' Net Value Per Share (A)']

 Per Share Net profit before tax (Yuan ¥) is highly correlated with: 

In [ ]:
Company_data_reduced = Company_data_df.drop(columns=to_drop)
print("Shape before:", Company_data_df.shape)
print("Shape after:", Company_data_reduced.shape)
print(f"\nWe now have two datasets. Orifinal dataset with {Company_data_df.shape[1]} columns and reduced dataset with {Company_data_reduced.shape[1]}.\nWe will be using both dataset to check how model perfroms with these datasets")

Shape before: (6819, 96)
Shape after: (6819, 77)

We now have two datasets. Orifinal dataset with 96 columns and reduced dataset with 77.
We will be using both dataset to check how model perfroms with these datasets


####Target variable class imbalance

In [ ]:
class_percentages = Company_data_df['Bankrupt?'].value_counts(normalize=True) * 100
class_percentages = class_percentages.round(2)


for cls, pct in class_percentages.items():
    print(f"Class {cls}: {pct:.2f}%")

print("\nThe dataset is highly imbalanced, because the minority class (Class 1) is severely underrepresented.")


Class 0: 96.77%
Class 1: 3.23%

The dataset is highly imbalanced, because the minority class (Class 1) is severely underrepresented.


In [ ]:
from sklearn.model_selection import train_test_split

Company_data_df_X = Company_data_df.drop('Bankrupt?', axis=1)
Company_data_df_y = Company_data_df['Bankrupt?']

Company_data_df_X_train, Company_data_df_X_test, Company_data_df_y_train, Company_data_df_y_test = train_test_split(
Company_data_df_X, Company_data_df_y, test_size=0.2, stratify=Company_data_df_y, random_state=42)


Company_data_reduced_X = Company_data_reduced.drop('Bankrupt?', axis=1)
Company_data_reduced_y = Company_data_reduced['Bankrupt?']

Company_data_reduced_X_train, Company_data_reduced_X_test, Company_data_reduced_y_train, Company_data_reduced_y_test = train_test_split(
Company_data_reduced_X, Company_data_reduced_y, test_size=0.2, stratify=Company_data_reduced_y, random_state=42)

In [ ]:
#Use SMOTE (Synthetic Minority Oversampling Technique) on original dataset
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
Company_data_df_X_train_SMOTE, Company_data_df_y_train_SMOTE = smote.fit_resample(Company_data_df_X_train, Company_data_df_y_train)

print("Before SMOTE:", Company_data_df_y_train.value_counts(normalize=True) * 100)
print("After SMOTE:", Company_data_df_y_train_SMOTE.value_counts(normalize=True) * 100)

Before SMOTE: Bankrupt?
0    96.773602
1     3.226398
Name: proportion, dtype: float64
After SMOTE: Bankrupt?
0    50.0
1    50.0
Name: proportion, dtype: float64


In [ ]:
#Use SMOTE (Synthetic Minority Oversampling Technique) on reduced (coorelated columns dropped) dataset
smote = SMOTE(random_state=42)
Company_data_reduced_X_train_SMOTE, Company_data_reduced_y_train_SMOTE = smote.fit_resample(Company_data_reduced_X_train, Company_data_reduced_y_train)

print("Before SMOTE:", Company_data_reduced_y_train.value_counts(normalize=True) * 100)
print("After SMOTE:", Company_data_reduced_y_train_SMOTE.value_counts(normalize=True) * 100)
print("\n\nNow target class inbalance for both dataset (original and reduced) has been handeled using SMOTE.")

Before SMOTE: Bankrupt?
0    96.773602
1     3.226398
Name: proportion, dtype: float64
After SMOTE: Bankrupt?
0    50.0
1    50.0
Name: proportion, dtype: float64


Now target class inbalance for both dataset (original and reduced) has been handeled using SMOTE.


####Logistic Regression

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, f1_score, classification_report

# Train Logistic Regression with original dataset
lr_model_df = LogisticRegression(solver='liblinear', random_state=42)
lr_model_df.fit(Company_data_df_X_train_SMOTE, Company_data_df_y_train_SMOTE)

# Step 4: Make predictions
lr_model_df_y_pred = lr_model_df.predict(Company_data_df_X_test) #Company_data_df_y_test

# Step 5: Evaluate
lr_acc = accuracy_score(Company_data_df_y_test, lr_model_df_y_pred)
lr_prec = precision_score(Company_data_df_y_test, lr_model_df_y_pred)
lr_f1 = f1_score(Company_data_df_y_test, lr_model_df_y_pred)
lr_cm = confusion_matrix(Company_data_df_y_test, lr_model_df_y_pred)

# Print results
print("Logistics regression modle performance trained with original dataset")
print("----------------")
print("\nConfusion Matrix:\n", lr_cm)
print(f"\nAccuracy: {lr_acc:.2f}")
print(f"Precision: {lr_prec:.2f}")
print(f"F1-Score: {lr_f1:.2f}")


print('-----------------------------')

# Train Logistic Regression with reduced dataset
lr_model_reduced = LogisticRegression(solver='liblinear', random_state=42)
lr_model_reduced.fit(Company_data_reduced_X_train_SMOTE, Company_data_reduced_y_train_SMOTE)

# Make predictions
lr_model_reduced_y_pred = lr_model_reduced.predict(Company_data_reduced_X_test)

# Evaluate
lr_acc_reduced = accuracy_score(Company_data_reduced_y_test, lr_model_reduced_y_pred)
lr_prec_reduced = precision_score(Company_data_reduced_y_test, lr_model_reduced_y_pred)
lr_f1_reduced = f1_score(Company_data_reduced_y_test, lr_model_reduced_y_pred)
lr_cm_reduced = confusion_matrix(Company_data_reduced_y_test, lr_model_reduced_y_pred)

# Print results
print("\n\n\nLogistics regression modle performance trained with reduced dataset")
print("----------------")
print("\nConfusion Matrix:\n", lr_cm_reduced)
print(f"\nAccuracy: {lr_acc_reduced:.2f}")
print(f"Precision: {lr_prec_reduced:.2f}")
print(f"F1-Score: {lr_f1_reduced:.2f}")

Model_score = []
Model_score.append(("Logistics Regression", lr_acc_reduced, lr_prec_reduced,lr_f1_reduced,lr_cm_reduced))
print("\n\n\nWe can notice that both models lr_model_df trained with original dataset and lr_model_reduced trained with reduced dataset perfroms the same. \nFor future models we will be using the reduced dataset to minimize computation effort.")

Logistics regression modle performance trained with original dataset
----------------

Confusion Matrix:
 [[1019  301]
 [  28   16]]

Accuracy: 0.76
Precision: 0.05
F1-Score: 0.09
-----------------------------



Logistics regression modle performance trained with reduced dataset
----------------

Confusion Matrix:
 [[1019  301]
 [  28   16]]

Accuracy: 0.76
Precision: 0.05
F1-Score: 0.09



We can notice that both models lr_model_df trained with original dataset and lr_model_reduced trained with reduced dataset perfroms the same. 
For future models we will be using the reduced dataset to minimize computation effort.



Confusion Matrix:
 [[1019  301]
 [  28   16]]

Accuracy: 0.76
Precision: 0.05
F1-Score: 0.09

####K-Nearest Neighbors

In [ ]:
from sklearn.neighbors import KNeighborsClassifier


# Train KNN with reduced dataset
knn_model_reduced = KNeighborsClassifier(n_neighbors=5)
knn_model_reduced.fit(Company_data_reduced_X_train_SMOTE, Company_data_reduced_y_train_SMOTE)

knn_model_reduced_y_pred = knn_model_reduced.predict(Company_data_reduced_X_test)

# Evaluate
knn_acc_reduced = accuracy_score(Company_data_reduced_y_test, knn_model_reduced_y_pred)
knn_prec_reduced = precision_score(Company_data_reduced_y_test, knn_model_reduced_y_pred)
knn_f1_reduced = f1_score(Company_data_reduced_y_test, knn_model_reduced_y_pred)
knn_cm_reduced = confusion_matrix(Company_data_reduced_y_test, knn_model_reduced_y_pred)

# Print results
print("\n\n\nk-nearest neighbors (KNN) modle performance trained with reduced dataset")
print("\nConfusion Matrix:\n", knn_cm_reduced)
print(f"\nAccuracy: {knn_acc_reduced:.2f}")
print(f"Precision: {knn_prec_reduced:.2f}")
print(f"F1-Score: {knn_f1_reduced:.2f}")

Model_score.append(("K-Nearest Neighbors",knn_acc_reduced, knn_prec_reduced,knn_f1_reduced,knn_cm_reduced))




k-nearest neighbors (KNN) modle performance trained with reduced dataset

Confusion Matrix:
 [[1134  186]
 [  28   16]]

Accuracy: 0.84
Precision: 0.08
F1-Score: 0.13


####Decision Tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier

# Train Decision Tree Classifier with reduced dataset
dtc_model_reduced = DecisionTreeClassifier(random_state=42)
dtc_model_reduced.fit(Company_data_reduced_X_train_SMOTE, Company_data_reduced_y_train_SMOTE)

dtc_model_reduced_y_pred = dtc_model_reduced.predict(Company_data_reduced_X_test)

# Evaluate
dtc_acc_reduced = accuracy_score(Company_data_reduced_y_test, dtc_model_reduced_y_pred)
dtc_prec_reduced = precision_score(Company_data_reduced_y_test, dtc_model_reduced_y_pred)
dtc_f1_reduced = f1_score(Company_data_reduced_y_test, dtc_model_reduced_y_pred)
dtc_cm_reduced = confusion_matrix(Company_data_reduced_y_test, dtc_model_reduced_y_pred)

# Print results
print("\n\n\nDecision Tree Classifier modle performance trained with reduced dataset")
print("\nConfusion Matrix:\n", dtc_cm_reduced)
print(f"\nAccuracy: {dtc_acc_reduced:.2f}")
print(f"Precision: {dtc_prec_reduced:.2f}")
print(f"F1-Score: {dtc_f1_reduced:.2f}")

Model_score.append(("Decision Tree Classifier",dtc_acc_reduced, dtc_prec_reduced,dtc_f1_reduced,dtc_cm_reduced))




Decision Tree Classifier modle performance trained with reduced dataset

Confusion Matrix:
 [[1253   67]
 [  23   21]]

Accuracy: 0.93
Precision: 0.24
F1-Score: 0.32


####Neural Networks

In [ ]:
from sklearn.neural_network import MLPClassifier

# Train Multi-Layer Perceptron with reduced dataset
mlp_model_reduced = MLPClassifier(
    hidden_layer_sizes=(64, 32),  # two hidden layers with 64 and 32 neurons
    activation='relu',            # common activation function
    solver='adam',                # optimizer
    max_iter=500,                 # increase iterations for convergence
    random_state=42
)
mlp_model_reduced.fit(Company_data_reduced_X_train_SMOTE, Company_data_reduced_y_train_SMOTE)

mlp_model_reduced_y_pred = mlp_model_reduced.predict(Company_data_reduced_X_test)

# Evaluate
mlp_acc_reduced = accuracy_score(Company_data_reduced_y_test, mlp_model_reduced_y_pred)
mlp_prec_reduced = precision_score(Company_data_reduced_y_test, mlp_model_reduced_y_pred)
mlp_f1_reduced = f1_score(Company_data_reduced_y_test, mlp_model_reduced_y_pred)
mlp_cm_reduced = confusion_matrix(Company_data_reduced_y_test, mlp_model_reduced_y_pred)

# Print results
print("\n\n\nMulti-Layer Perceptron modle performance trained with reduced dataset")
print("\nConfusion Matrix:\n", mlp_cm_reduced)
print(f"\nAccuracy: {mlp_acc_reduced:.2f}")
print(f"Precision: {mlp_prec_reduced:.2f}")
print(f"F1-Score: {mlp_f1_reduced:.2f}")

Model_score.append(("Multi-Layer Perceptron",mlp_acc_reduced, mlp_prec_reduced,mlp_f1_reduced,mlp_cm_reduced))




Multi-Layer Perceptron modle performance trained with reduced dataset

Confusion Matrix:
 [[1164  156]
 [  29   15]]

Accuracy: 0.86
Precision: 0.09
F1-Score: 0.14


####Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier

# Train Random Forest Classifier with reduced dataset
rfc_model_reduced = RandomForestClassifier(
    n_estimators=100,   # number of trees
    max_depth=None,     # let trees expand fully (can tune later)
    random_state=42
)
rfc_model_reduced.fit(Company_data_reduced_X_train_SMOTE, Company_data_reduced_y_train_SMOTE)

rfc_model_reduced_y_pred = rfc_model_reduced.predict(Company_data_reduced_X_test)

# Evaluate
rfc_acc_reduced = accuracy_score(Company_data_reduced_y_test, rfc_model_reduced_y_pred)
rfc_prec_reduced = precision_score(Company_data_reduced_y_test, rfc_model_reduced_y_pred)
rfc_f1_reduced = f1_score(Company_data_reduced_y_test, rfc_model_reduced_y_pred)
rfc_cm_reduced = confusion_matrix(Company_data_reduced_y_test, rfc_model_reduced_y_pred)

# Print results
print("\n\n\nRandom Forest Classifier modle performance trained with reduced dataset")
print("\nConfusion Matrix:\n", rfc_cm_reduced)
print(f"\nAccuracy: {rfc_acc_reduced:.2f}")
print(f"Precision: {rfc_prec_reduced:.2f}")
print(f"F1-Score: {rfc_f1_reduced:.2f}")

Model_score.append(("Random Forest Classifier",rfc_acc_reduced, rfc_prec_reduced,rfc_f1_reduced,rfc_cm_reduced))




Random Forest Classifier modle performance trained with reduced dataset

Confusion Matrix:
 [[1286   34]
 [  20   24]]

Accuracy: 0.96
Precision: 0.41
F1-Score: 0.47


####

####Gradient Boosting

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

# Train Gradient Boosting Classifier with reduced dataset
gb_model_reduced = GradientBoostingClassifier(
    n_estimators=200,   # number of boosting stages (trees)
    learning_rate=0.1,  # step size (smaller = more robust, slower)
    max_depth=3,        # depth of each tree
    random_state=42
)

gb_model_reduced.fit(Company_data_reduced_X_train_SMOTE, Company_data_reduced_y_train_SMOTE)

gb_model_reduced_y_pred = gb_model_reduced.predict(Company_data_reduced_X_test)

# Evaluate
gb_acc_reduced = accuracy_score(Company_data_reduced_y_test, gb_model_reduced_y_pred)
gb_prec_reduced = precision_score(Company_data_reduced_y_test, gb_model_reduced_y_pred)
gb_f1_reduced = f1_score(Company_data_reduced_y_test, gb_model_reduced_y_pred)
gb_cm_reduced = confusion_matrix(Company_data_reduced_y_test, gb_model_reduced_y_pred)

# Print results
print("\n\n\nGradient Boosting Classifier modle performance trained with reduced dataset")
print("\nConfusion Matrix:\n", gb_cm_reduced)
print(f"\nAccuracy: {gb_acc_reduced:.2f}")
print(f"Precision: {gb_prec_reduced:.2f}")
print(f"F1-Score: {gb_f1_reduced:.2f}")

Model_score.append(("Gradient Boosting Classifier",gb_acc_reduced, gb_prec_reduced,gb_f1_reduced,gb_cm_reduced))




Gradient Boosting Classifier modle performance trained with reduced dataset

Confusion Matrix:
 [[1276   44]
 [  19   25]]

Accuracy: 0.95
Precision: 0.36
F1-Score: 0.44


####Comparison of Results

In [ ]:
Model_Score_df = pd.DataFrame(Model_score, columns=["Model", "Accuracy", "Precision", "F1 Score", "Confusion Matrix"])

In [ ]:
Model_Score_df.style.format({
    "Accuracy": "{:.2f}",
    "Precision": "{:.2f}",
    "F1 Score": "{:.2f}"
})

####Conclusion

In [ ]:
print("We can notice that Random Forest Classifier and Gradient Boosting Classifier are better perfroming models")
print(f"\nRandom Forest Classifier has an accuracy of {rfc_acc_reduced:.2f}, precision of {rfc_prec_reduced:.2f}, and F1 score of {rfc_f1_reduced:.2f} \nGradient Boosting Classifier has an accuracy of {gb_acc_reduced:.2f}, precision of {gb_prec_reduced:.2f}, and F1 score of {gb_f1_reduced:.2f}.")

We can notice that Random Forest Classifier and Gradient Boosting Classifier are better perfroming models

Random Forest Classifier has an accuracy of 0.96, precision of 0.41, and F1 score of 0.47 
Gradient Boosting Classifier has an accuracy of 0.95, precision of 0.36, and F1 score of 0.44.


####References

  - 5 Minutes Engineering youtube channel for machine learning algorithns.
  - ChatGPT for cooding assistance.

<font size=+2 color="blue"><center><b> End of project</b></center></font>